import { ResultMessage } from "../../../interfaces/ResultMessage";

export const ResultCodeMap = {
    [ResultMessage.SUCCESS]:"SUCCESS",
    [ResultMessage.FAILED]:"FAILED",

    [ResultMessage.FAILED_ROOM_NOT_EXISTS_ROOM]:"FAILED_ROOM_NOT_EXISTS_ROOM",
    [ResultMessage.FAILED_ROOM_ALREADY_EXISTS_ROOM]:"FAILED_ROOM_ALREADY_EXISTS_ROOM",
    [ResultMessage.FAILED_ROOM_NOT_IN_ROOM]:"FAILED_ROOM_NOT_IN_ROOM",

    [ResultMessage.FAILED_GROUP_NOT_EXISTS_GROUP]:"FAILED_GROUP_NOT_EXISTS_GROUP",
    [ResultMessage.FAILED_GROUP_NOT_IN_GROUP]:"FAILED_GROUP_NOT_IN_GROUP",
    [ResultMessage.FAILED_GROUP_ALREADY_EXISTS_GROUP]:"FAILED_GROUP_ALREADY_EXISTS_GROUP",
    [ResultMessage.FAILED_GROUP_SAME_GROUP]:"FAILED_GROUP_SAME_GROUP",
    [ResultMessage.FAILED_GROUP_NOT_EXISTS_PLAYER]:"FAILED_GROUP_NOT_EXISTS_PLAYER",
    [ResultMessage.FAILED_GROUP_ALREADY_EXISTS_PLAYER]:"FAILED_GROUP_ALREADY_EXISTS_PLAYER"
}